### PR TITLE
run command

### PR DESCRIPTION
**Pull request by soupi**
will build and run ./output/Main's main function using node -e

### CODE REVIEW

**Comment by hdgarrood** [comment]
Pulp might already be able to do this via the `--dependency-path` option, and if not I'd certainly consider making changes to Pulp to better accommodate psc-package; I think we risk duplicating effort by going down this route.

**Comment by soupi** [comment]
@hdgarrood I do agree with you on the long run, but considering how simple this change is and how much it adds to ergonomics I'd like you to consider adding this feature. :)

**Comment by hdgarrood** [comment]
I think it's just a waste of effort, and it won't be nice for people trying to use this if they get used to using `psc-package run` but then we later decide to remove it again. I think it shouldn't be too hard to work out how to get Pulp to support this, and it probably won't take that much time, either; making a new Pulp release is easy.

Pulp no longer implements `pulp run` like this because doing it this way led to one or two bugs, I don't remember the details exactly (you'll have to dig through the Pulp issue tracker).

**Comment by paf31** [comment]
I think Pulp is specialized for JS use, while `psc-package` is supposed to be more general. So this might be useful, but on the other hand it's a feature which won't work with the C++ and Erlang backends which already use `psc-package`.

I would rather document how to use `psc-package sources` to create a script to support this use case.

**Comment by soupi** [comment]
Alright, no problem. I'll close this off then.

**Comment by paf31** [comment]
I know we could say the same things about the `repl` and `build` commands, by the way, but I'm hoping we can solve those things later. Maybe the solution is to remove those too and encourage people to use `psc-package sources`, but I'm not sure.

**Comment by soupi** [comment]
It is possible to have yet another specialized tool that wraps over psc-package functionality and provides simple commands like `build`, `repl` and `run` by invoking psc-package that can be specialized for each backend (or a Makefile that does that). But I don't think psc-package will be usable enough for less advanced people without any of those.

I've noticed that a few people jump straight into PureScript trying to use psc-package because it doesn't require bower for some reason or another. I'd be great if we could provide them with an easy experience while still achieving the goals for psc-package.

**Comment by paf31** [comment]
Yes, I'm torn. It does make sense to support the JS backend, since it is the main backend after all. And since `psc-package` is basically just a glorified shell script anyway, maybe it does make sense to add these things, rather than having layers and layers of scripts.

**Comment by soupi** [comment]
I feel your pain :)

**Comment by andyarvanitis** [comment]
FYI, the default C++ backend `Makefile` uses `psc-package sources` and supports building and running the built executable. It generally works fine with `psc` too for building, at least, (you can try it by using `PCC=psc`). But I don't use it that much with `psc`, other than for occasionally comparing codegen output. Note that I'm not a major "`make` guy" , so I'm not advocating anything with this info, just providing it since it was mentioned:

https://github.com/pure11/pure11/blob/pure11/pcc/support/Makefile

**Pull request closed without merging**
