### PR TITLE
Bump turtle version

### PR DESCRIPTION
**Pull request by paluh**

### CODE REVIEW

**Comment by paluh** [comment]
I've found now that there is separate similar PR, but my proposition doesn't break compilation with current turtle version (`turtle==1.3.*`). I've changed `nub` calls to explicit usage of `List.nub` and have changed dependency from `turtle == 1.3.*` to `turtle >= 1.3`.

**Comment by justinwoo** [comment]
@paluh I've updated master with < 1.6. Does this suit your needs?

**Comment by paluh** [comment]
@justinwoo Yes!

**Comment by justinwoo** [comment]
I'll close this as this seems to have been addressed.

**Pull request closed without merging**
