### PR TITLE
doc generation through `purs docs`

### PR DESCRIPTION
**Pull request by matthewleon**
addresses #48

### CODE REVIEW

**Comment by paf31** [comment]
@hdgarrood Any thoughts on this in the context of possibly adding support for `psc-package` to Pulp?

**Comment by hdgarrood** [comment]
The psc-package support for pulp is close to being done, and it will cover this use case, so if you'd rather not add this to psc-package I think that's probably okay.

**Comment by matthewleon** [comment]
For what it's worth I don't feel strongly either way, this just felt like it somehow completed the suite of commands offered that run `purs` subcommands using the paths from `psc-package`.

**Comment by paf31** [comment]
Ok, let's leave this open until Pulp gets psc-package support then, at which point we can decide. Thanks!

**Comment by hdgarrood** [comment]
Shall we close this too? see #48.

**Comment by matthewleon** [comment]
> Shall we close this too

yes

**Pull request closed without merging**
