### PR TITLE
Combine update into the build and repl commands

### LINKED ISSUE #31: Consider if the subcommands `update` and `updates` are too similar
It's not a big deal, but I think having commands that only differ by `s` might be confusing.

### LINKED ISSUE #32: Consider folding the `update` command into `build`
This would make `psc-package build` more declarative by not having it depend on whether you've run `psc-package update` or not. Stack does it and it's really nice. Would this be a good change?

### PR DESCRIPTION
**Pull request by paf31**
fix #31 
fix #32

### CODE REVIEW

**Comment by seagreen** [comment]
Just checking: I think this will print:
```
Updating foreign
Updating fork
Updating foreign
Updating fork
Updating form-urlencoded
Updating free
<etc>
```

on every `psc-package build`. Those messages should probably only be printed if something actually was done for a package.

**Comment by paf31** [comment]
Good point, thanks!

**Comment by paf31** [comment]
How's this?

**Comment by seagreen** [comment]
That looks perfect=)

**Pull request merged**
