### PR TITLE
Simplify verification instructions

### PR DESCRIPTION
**Pull request by gasi**
To be used in conjunction with: https://github.com/purescript/package-sets/pull/253

### CODE REVIEW

**Comment by justinwoo** [comment]
I don't understand, why run the travis script when you're meant to run the psc-package verify [package] command?

**Comment by gasi** [comment]
If you look at the docs, they tell you to do all the steps that `travis.sh` already does, so I meant to extend the script so it could handle all cases, e.g. `./travis.sh` (no arguments) verifies all packages and `./travis.sh <package>`, e.g. `./travis.sh aff`, will check just that one as outlined in the docs.

Long-term, I imagine it might be better to name the script `./verify.sh` or similar instead of Travis to avoid the confusion.

Does that make sense?

**Comment by justinwoo** [comment]
Oh, sorry, I forgot that there's no equivalent to `make setup` I have in Spacchetti for Package-Sets (https://github.com/spacchetti/spacchetti/blob/cc9da23ee67a87369983cb6de16458c4d60fc1b5/Makefile#L16-L22)

So it seems like what should be fixed is to add a make file or something for the package-sets repo to make the test setup actually work.

**Comment by justinwoo** [comment]
Package-sets now has a makefile to do setup of the testing. Can this close?

**Pull request closed without merging**
