### PR TITLE
Add deprecation notice

### PR DESCRIPTION
**Pull request by f-f**
See https://github.com/spacchetti/spago/issues/423

### CODE REVIEW

**Comment by justinwoo** [comment]
I don't think the wording is very nice or necessarily accurate, but sure

**Comment by f-f** [comment]
@justinwoo I have no opinion on the wording, I just picked the notice from [`purify`](https://github.com/chrisdone/purify), that redirects here

**Comment by hdgarrood** [comment]
What is inaccurate about it?

**Comment by hdgarrood** [comment]
The deprecation notice should probably mention the extent to which users can expect `psc-package` to receive updates going forward (e.g. none at all, or just bug fixes, or something else). Other than that I think this looks good.

**Comment by f-f** [comment]
@hdgarrood @justinwoo any suggestions for the new wording?

**Comment by hdgarrood** [comment]
I think we might need to step back a bit and check that we actually align on the higher-level goals here. @justinwoo: is `psc-package` receiving any updates these days? If it is, is it just bug fixes? Do you agree with deprecating `psc-package`?

**Comment by justinwoo** [comment]
honestly, i think the one major feature that psc-package is missing is that specifying a local package set should be as easy as giving a filepath for "set". other than that i do not expect that there are many features to add, if any, since the appeal of this tool is that it does exactly what is on the tin. i don't think applying the "deprecated" label is so fitting here though, since any proposed replacements to come are not in the same vein.

do i plan to update this? maybe. i would like to, but i'm also not the most motivated person ever.

-----

however, there are a few things we can probably agree on:

* many users seem to prefer using spago as an overall solution rather than psc-package + pulp

* psc-package will likely not try to adopt some features like publishing packages

* psc-package doesn't really need to be in the purescript organization on github, as it's not an "official" project, whereas package-sets is somewhat centrally managed.

considering this, we should update this README and suggest that users might want to use spago, and we might consider moving psc-package out of purescript and more fittingly into purescript-contrib or such.  *edit: being on the purescript organization currently, there is a high likelihood of people assuming that psc-package is the one and main way of installing dependencies and managing purescript projects.

**Comment by justinwoo** [comment]
i know the contribution graph can be misleading because i seem to have the most commits on this repo, since i have contributed some fixes and also introduced and removed a broken feature (add-from-bower), but i should say this isn't solely my project, so i don't really want to move this into my profile as some have suggested, and i hope it isn't so much of a desire from others to do so.

**Comment by hdgarrood** [comment]
Not deprecating `psc-package`, but instead mentioning spago in the readme and moving this repo to `purescript-contrib` sounds good to me.

**Comment by f-f** [comment]
@hdgarrood sounds great to me. I'd also like to see specified a policy about which kinds of contributions (ideas/bugfixes/features) are going to be considered and/or merged - i.e. clearly writing down the fact that as Justin mentioned above "there are no features to add"

This has come up before in various online discussions and is the main reason for the existence of Spago, where instead all contributions/ideas are welcome (and this is fine, having a feature-frozen codebase is valuable as long as it is clearly communicated)
I feel that leaving this unspecified would continue to confuse people and fail to provide the needed historical context here.

I'm going to close this PR since the original wording is not relevant anymore

**Pull request closed without merging**
