### PR TITLE
Fix Windows only problem of wrapper command built by npm

### PR DESCRIPTION
**Pull request by taiju**
rel: #34, #69, #138 

-- I'm sorry. I'm not good at English.

psc-package command can't exec `purs`, if it is installed by npm command.

Although I tried to solve it, I found that it is a constraint of `System.Process.createProcess` or `System.Process.runProcess`.

- https://github.com/haskell/process/issues/140

It works if instead use `System.Process.shell` or `System.Process.runCommand`.

This PR is another approach of #69.

Thank you.

### CODE REVIEW

**Comment by justinwoo** [comment]
This makes `psc-package build` not work for me on Linux, where I have a `purs` binary only. Problem seems to be from the source globs not being passed in correctly.

**Comment by justinwoo** [comment]
E.g. one test run I tried results in this:

```
psc-package: ShellFailed {shellCommandLine = "purs compile .psc-package/testing/arrays/v5.1.0/src/**/*.purs .psc-package/testing/bifunctors/v4.0.0/src/**/*.purs .psc-package/testing/control/v4.1.0/src/**/*.purs .psc-package/testing/distributive/v4.0.0/src/**/*.purs .psc-package/testing/effect/v2.0.0/src/**/*.purs .psc-package/testing/either/v4.1.0/src/**/*.purs .psc-package/testing/enums/v4.0.0/src/**/*.purs .psc-package/testing/exceptions/v4.0.0/src/**/*.purs .psc-package/testing/foldable-traversable/v4.1.0/src/**/*.purs .psc-package/testing/foreign/v5.0.0/src/**/*.purs .psc-package/testing/foreign-object/v1.1.0/src/**/*.purs .psc-package/testing/functions/v4.0.0/src/**/*.purs .psc-package/testing/gen/v2.1.0/src/**/*.purs .psc-package/testing/globals/v4.0.0/src/**/*.purs .psc-package/testing/identity/v4.1.0/src/**/*.purs .psc-package/testing/integers/v4.0.0/src/**/*.purs .psc-package/testing/invariant/v4.1.0/src/**/*.purs .psc-package/testing/lazy/v4.0.0/src/**/*.purs .psc-package/testing/lists/v5.3.0/src/**/*.purs .psc-package/testing/math/v2.1.1/src/**/*.purs .psc-package/testing/maybe/v4.0.0/src/**/*.purs .psc-package/testing/newtype/v3.0.0/src/**/*.purs .psc-package/testing/nonempty/v5.0.0/src/**/*.purs .psc-package/testing/nullable/v4.1.0/src/**/*.purs .psc-package/testing/orders/v4.0.0/src/**/*.purs .psc-package/testing/partial/v2.0.0/src/**/*.purs .psc-package/testing/prelude/v4.1.0/src/**/*.purs .psc-package/testing/proxy/v3.0.0/src/**/*.purs .psc-package/testing/record/v1.0.0/src/**/*.purs .psc-package/testing/refs/v4.1.0/src/**/*.purs .psc-package/testing/simple-json/v4.3.0/src/**/*.purs .psc-package/testing/st/v4.0.0/src/**/*.purs .psc-package/testing/strings/v4.0.1/src/**/*.purs .psc-package/testing/tailrec/v4.0.0/src/**/*.purs .psc-package/testing/transformers/v4.1.0/src/**/*.purs .psc-package/testing/tuples/v5.1.0/src/**/*.purs .psc-package/testing/type-equality/v3.0.0/src/**/*.purs .psc-package/testing/typelevel-prelude/v3.0.0/src/**/*.purs .psc-package/testing/unfoldable/v4.0.0/src/**/*.purs .psc-package/testing/unsafe-coerce/v4.0.0/src/**/*.purs .psc-package/testing/variant/v5.2.0/src/**/*.purs", shellExitCode = ExitFailure 1}
```

Maybe the problem arises from these source globs not being quoted?

**Comment by justinwoo** [comment]
It seems you'd have to fiddle with both String and Text related code to quote all of these (e.g. https://github.com/justinwoo/psc-package/commit/e008bd930aac52059a437791c3543a9ca5280a8a), and it still feels a bit iffy as you can pass through options to the compiler. Maybe someone will have another opinion about this.

**Comment by taiju** [comment]
Well, I see...
I will try another approach.
Do you think that it is worth keeping this approach?

**Comment by taiju** [comment]
I understood that there are many problems this PR. I'll rethink. Thank you for your reviewing!

**Pull request closed without merging**
